### ISSUE TITLE
support a better demo flow

### ISSUE THREAD

**Issue by carlsverre** [singlestore-labs/demo-realtime-digital-marketing#13]
desired flow is something like:
1. fully running application -> sell business case and talk about the idea
2. jump to overview - in the process data is cleared and overview is ready to walk through
3. bring it full circle back to the application and analytics

**Comment by ricochet** [comment]
At ECGC this is the natural flow we landed on. The map view is very nice as the main display continuously running until we dive into a demo.

In the overview, my preference is that the reset does not involve dropping the DB and rebuild the schemas. That 20ish seconds can really kill the flow.
